### ISSUE TITLE
Disabling auto key mappings?

### ISSUE THREAD

**Issue by rafi** [kshenoy/vim-signature#102]
Is it possible to disable all the keyboard mappings and configure them manually?

**Comment by kshenoy** [comment]
Take a look at [this](https://github.com/kshenoy/vim-signature/blob/367a28175ac59f1fcbff87fb8f4ee5c66e74b1dc/doc/signature.txt#L91-L122)

**Comment by rafi** [comment]
I've tried that, but `vim-signature` still binds itself to some mappings I don't want it to:
```viml
:verbose nmap '[
n  '[          * :<C-U>call signature#mark#Goto("prev", "line", "alpha")<CR>
        Last set from ~/.cache/vim/plugins/vim-signature/plugin/signature/utils.vim
```
When using:
```viml
let g:SignatureMap = {
	\ 'Leader': 'm',
	\ 'PlaceNextMark': 'm,',
	\ 'ToggleMarkAtLine': 'm.',
	\ 'PurgeMarksAtLine': 'm-',
	\ 'ListLocalMarks': 'm/',
	\ 'ListLocalMarkers': 'm?'
	\ }
```

**Comment by kshenoy** [comment]
> To disable a map entirely, specify it as an empty string.
> If a key is not specified, the default value will be picked up.

The way you have configured `g:SignatureMap` will not result in a different behavior. The plugin will see that you have created customisations for Leader, PlaceNextMark, ToggleMarkAtLine etc. and use what you've set it up as. As for the rest, it'll just pick up the defaults.

`g:SignatureMap` should be used to specify what you want to override. If you want to disable `'[` then you should specify

````
let g:SignatureMap = {
\ 'GotoPrevLineAlpha'  :  ""
\ }
````

**Comment by rafi** [comment]
Thank you, this works for me.
