### ISSUE TITLE
Recover from accidental m<Space>?

### ISSUE THREAD

**Issue by udopt** [kshenoy/vim-signature#103]
Is there a way to recover from an accidental `m<Space>`?

**Comment by kshenoy** [comment]
Nope, but there's a [way to be a little more careful](https://github.com/kshenoy/vim-signature/blob/367a28175ac59f1fcbff87fb8f4ee5c66e74b1dc/doc/signature.txt#L266-L270) in the future. See if that works for the case you have in mind.

**Comment by udopt** [comment]
Thanks, enabling `g:SignaturePurgeConfirmation` does the job for me.
