### ISSUE TITLE
Don't delete marks you don't manage

### ISSUE THREAD

**Issue by nedbat** [kshenoy/vim-signature#107]
I use global marks (capital letters) for fixed files that I need to visit often.  I don't need to see those marks, so I set:
```
let g:SignatureIncludeMarks = 'abcdefghijklmnopqrstuvwxyz'
```
I was using `m<Space>` to clear the mark gutter, and was later confused why some of my global marks were missing.  Of course, it's because `m<Space>` clears all marks, including the global mark for the file.

I think it would make sense for `m<Space>` to only affect the marks that Signature manages, so only those in the SignatureIncludeMarks list.

**Comment by kshenoy** [comment]
Hmm, I don't face this issue. Can you use `:marks` before and after pressing `m<Space>` to confirm if the global mark is actually removed by Signature?

Also, can you try starting vim with only Signature installed using `gvim -N -u <(echo 'set rtp+=~/.vim/bundle/vim-signature/') -U NONE` command and repeating the same experiment?

**Comment by nedbat** [comment]
Hmm, your experiments shows that the global mark is not deleted... Odd.  I only lost global marks after I learned about `m<space>`, so I associated the two.  Sorry to keep being the bearer of mysterious effects!

**Comment by kshenoy** [comment]
Haha, no problem. Glad that it worked out.
