### ISSUE TITLE
Undefined variable: SignatureMarkText

### ISSUE THREAD

**Issue by wyne** [kshenoy/vim-signature#109]
Just installed fresh. Whenever I try to set a mark, I get this error:

```
E121: Undefined variable: SignatureMarkerText
E15: Invalid expression: SignatureMarkerText
Error detected while processing function signature#sign#Refresh..signature#sign#Place..<SNR>117_RefreshLine..<SNR>117_EvaluateHL:
line    2:
E121: Undefined variable: SignatureMarkText
E15: Invalid expression: SignatureMarkText
48;5;235mPress ENTER or type command to continue
```

**Comment by kshenoy** [comment]
Hmm, this doesn't make sense. Did you put anything in your vimrc to get this working?

Can you start vim using the following command `gvim -N -u <(echo 'set rtp+=~/.vim/bundle/vim-signature/') -U NONE` and see if you still get the error?

Can you point me to your vimrc?

**Comment by wyne** [comment]
Hm, the error doesn't happen when i use that command. Maybe some other plugin I have installed is interfering.

I'm using neovim and my config is here:
https://github.com/wyne/dotfiles/blob/master/vim/.nvimrc

**Comment by kshenoy** [comment]
Your rc file doesn't have any Signature related stuff in it. So I can't comment on it.

The reason I say it's weird is because I don't use variables named `SignatureMarkText` or `SignatureMarkerText`. 

If you can figure out if it's due to interaction with some other plugin and which plugin it is it'd be a great help

**Comment by wyne** [comment]
Oh, looks like the `morhetz/gruvbox` and/or `mhinz/vim-signify` is causing the issue. Sorry for the false alarm and hanks for the quick response!

**Comment by wyne** [comment]
Related: https://github.com/morhetz/gruvbox/issues/38

**Comment by kshenoy** [comment]
Umm, I'm not sure how Gruvbox is at fault here. Their code looks fine. Let me dig deeper. 

Can you tell me if you get the error by starting vim like this:

    gvim -N -U NONE -u <(cat << VIMRC
    filetype plugin indent on
    set rtp+=~/.vim/bundle/vim-signature
    set rtp+=~/.vim/bundle/gruvbox
    colorscheme gruvbox
    VIMRC)

**Comment by wyne** [comment]
Running like this:
``` vim
nvim -N -U NONE -u <(echo '
filetype plugin indent on
set rtp+=~/.config/nvim/bundle/vim-signature
set rtp+=~/.config/nvim/bundle/gruvbox
colorscheme gruvbox')
```

And as soon as it open, I do `ma` to set a mark:

``` vim
line   22:
W18: Invalid character in group name
Press ENTER or type command to continue
```

**Comment by kshenoy** [comment]
Can you try updating to the latest version and trying again? I put in some fixes that I think could be related to your issue.

**Comment by wyne** [comment]
vim-signature: 47ceaf9cbd970450953bdf3e84e281473a579ac0
gruvbox: 91bae6876031ececf151cc4f28aa5fb8c93681e4

Running with just gruvbox and vim-signature enabled, it's working fine now. Progress!

Though when I use [my full vimrc](https://github.com/wyne/dotfiles/blob/master/vim/.nvimrc), I get this error when doing `ma` on a new buffer:

``` vim
E116: Invalid arguments for function has_key(b:sy.internal, a:lnum)
E15: Invalid expression: has_key(b:sy.internal, a:lnum)
Press ENTER or type command to continue
```

I'm not very familiar with how to debug these things, other than turning off other plugins.

**Comment by wyne** [comment]
Everything is working fine on existing files as opposed to new buffers, though. Not sure if that's meaningful or not.

**Comment by kshenoy** [comment]
Can you please paste the contents of your full vimrc? The previous paste did not have signature install line or any signature related settings.

**Comment by kshenoy** [comment]
Ok, I think I figured out what's wrong. Please try now.

**Comment by wyne** [comment]
Updated to 17809dedb451814dfffe86069a479e5a41f109d5 and no errors.

Thanks so much!
