### ISSUE TITLE
conflicts with git plugins

### ISSUE THREAD

**Issue by acornejo** [kshenoy/vim-signature#113]
When used with either `junegunn/gv.vim` or `gregsexton/gitv` this plugin causes a highlighting problem where all whitespace in a commit is highlighted as a search match.

To reproduce simply install either of the aformentioned plugins and when inside a gitrepo execute either `:GV` or `:Gitv` respectively.

**Comment by kshenoy** [comment]
Umm, it works for me. Can you post a screenshot of the highlighting issue?

**Comment by acornejo** [comment]
![screen shot 2016-10-16 at 11 39 09 am](https://cloud.githubusercontent.com/assets/83786/19419868/3210c8a2-9395-11e6-9055-3fb3587f6609.png)

Sure thing. I've actually ended up disabling vim-signature because of it :(

**Comment by acornejo** [comment]
If I remove this line the problem goes away:

https://github.com/kshenoy/vim-signature/blob/537651a3a6dac10442f3e5ea2bb55a0bfd3324a6/plugin/signature.vim#L55

**Comment by kshenoy** [comment]
That's weird. Were you able to figure out why that was happening?
