### ISSUE TITLE
When add/remove a mark, it doesn't automatically appear on the left

### ISSUE THREAD

**Issue by snitko** [kshenoy/vim-signature#114]
When add/remove a mark, it doesn't automatically appear on the left and I have to invoke `:SignatureRefresh` manually in order for that to happen. Is there a way to avoid that?

**Comment by kshenoy** [comment]
Hi, sorry for the late response; I've been busy with work. 

That's weird, can you tell me the output of `:echo g:SignaturePeriodicRefresh` and `:set updatetime?` ?

**Comment by snitko** [comment]
I apologize, it looks like something wasn't properly installed, works just fine now.
