### ISSUE TITLE
Mark region background color

### ISSUE THREAD

**Issue by Samcfuchs** [kshenoy/vim-signature#116]
![image](https://cloud.githubusercontent.com/assets/6753408/15340880/c0dc2170-1c59-11e6-8f1c-05c026747e9c.png)

The background for the mark region is a very ugly grey on my system, which looks terrible with solarized and other dark themes. Is there, or can there be a command to change that color?

**Comment by kshenoy** [comment]
Hi, can you give it a try now. This should at least fix the different color background between's Signature's sign and the rest of the SignColumn itself. Both should now be the same color.

If by grey, you're referring to the column that is present to the left of the number column, then that is decided by the colorscheme you've loaded. See the output of `:highlight SignColumn`. It'll match the grey column.

If you want to change the color of just the background of the sign, then take a look at `:help g:SignatureMarkTextHL`

**Comment by Samcfuchs** [comment]
I was able to fix the color of the leftmost column by putting this line in my vimrc:

    hi SignColumn guibg=#002b36

But after messing around with some other colors, it did not seem like the background of the mark itself was updating appropriately. I'm not too worried, because the mark background seems to default to the text field background color, and that's what I set that column to.

**Comment by kshenoy** [comment]
> the mark background seems to default to the text field background color

Right, that was a bug I fixed. If the sign column and text field colors are different then the sign would look ugly. The new behavior is that the background of the mark will match the background of the sign column.

**Comment by Samcfuchs** [comment]
No, but the background of the mark should match the sign column, not the text field, right?

**Comment by kshenoy** [comment]
That's right. At least, that's what I'm trying to do when I donated a fix after you opened this bug.

Is this not what you're seeing?

**Comment by Samcfuchs** [comment]
Well, after I updated to your fix, the column was still grey. Unfortunately, I didn't take a screenshot, but it was the same as in the first screenshot. Then I added the line above to the vimrc to change the color of that column manually. After commenting it out and reloading the vimrc, this is what I got:

![image](https://cloud.githubusercontent.com/assets/6753408/15412833/012f1354-1df9-11e6-815b-fb797fffb854.png)

So it appears that it's not a latent setting, but that it's actually actively changing the color to that nasty gray.

**Comment by Portersson** [comment]
@Samcfuchs instead of changing the highlight colors to hex value, I think what you're looking for is setting them to 'none' which will make them follow the background.

I added this to my .vimrc
```
hi SignColumn guibg=none
hi SignColumn ctermbg=none
hi SignatureMarkText ctermbg=none

```

**Comment by kshenoy** [comment]
@Samcfuchs Let me reuse your screenshot.

![012f1354-1df9-11e6-815b-fb797fffb854](https://cloud.githubusercontent.com/assets/1559554/16709498/656a5324-45e0-11e6-8565-9511e705219a.png)

I've marked the SignColumn with two different colored rectangles. The green box is the portion of the SignColumn over which Signature has control over to decide the color of the foreground and the background. The red box is the portion of the SignColumn over which Signature does not have any control. This is controlled by your colorscheme.

If you want to change the color of the area inside the red box then you have to modify your colorscheme or do what @Portersson suggested.
