### ISSUE TITLE
Bad signature#utils#SetupHighlightGroups behaviour when synIDattr returns -1

### ISSUE THREAD

**Issue by gracjan-grala** [kshenoy/vim-signature#117]
After updating to the latest version (with [Fix for #116](https://github.com/kshenoy/vim-signature/commit/132a551572afa4e6fb1ed88b5c964cae12c33ff8)) I'm getting the following error when starting vim:
```
Error detected while processing function signature#utils#SetupHighlightGroups..CheckAndSetHL:
line    4:
E421: Color name or number not recognized: ctermbg=-1
```
I think [this](https://github.com/kshenoy/vim-signature/commit/132a551572afa4e6fb1ed88b5c964cae12c33ff8#diff-9c5029876950a74b848fde1d32b656caR143) is the line where it goes wrong:
```vim
let l:color=synIDattr(synIDtrans(hlID(a:set)), a:what, a:prefix)
```
`synIDattr` returns `-1` here, which I believe it shouldn't.
I found some Google Groups discussions mentioning the problem:
- https://groups.google.com/forum/#!topic/vim_dev/rUyy1SjbkbU
- https://groups.google.com/forum/#!searchin/vim_dev/synIDattr/vim_dev/S-x9R3NSi-c/ihv-vXAjFwAJ

These imply that it's not the intended behaviour, but apparently it's still not fixed, so maybe handling the `-1` case is necessary here.

Does anyone else have this issue?

**Comment by kshenoy** [comment]
That's weird. I tested it with made up highlight group names as well as cleared ones and I got a blank string everytime. Anyways, hope this additional boundary check works.

**Comment by gracjan-grala** [comment]
Thanks, that fixed it for me
