### ISSUE TITLE
Can't list

### ISSUE THREAD

**Issue by xushaobo** [kshenoy/vim-signature#118]
In my vim , the "m?" commond only can show marker !@#$%^&*(), it can't show mark 'x' at all.Anyone has meet this question?

**Comment by kshenoy** [comment]
Hi, `m?` displays only the markers. Use `m/` for a list of the marks. 

From the [help](https://github.com/kshenoy/vim-signature/blob/f89c3d433c83fabea91a56cf95030de4c2a6d91d/doc/signature.txt#L44-L52):

    m/           Open location list and display marks from current buffer
    m?           Open location list and display markers from current buffer

Hope this helps

**Comment by xushaobo** [comment]
Thanks😙

2016-06-02 11:10 GMT+08:00 Kartik Shenoy <notifications@github.com>:
