### ISSUE TITLE
How do you always show the marker area?

### ISSUE THREAD

**Issue by krzkrzkrz** [kshenoy/vim-signature#119]
How do you always show the marker area? Even if there are no markers set

**Comment by kshenoy** [comment]
I don't. If Signature is the only plugin that places signs, then the SignColumn will only be visible if there are any marks/markers.

Here's what it looks like with a marker:
![withmarker](https://cloud.githubusercontent.com/assets/1559554/15806393/5c19814a-2b10-11e6-85b4-96acd8836e94.PNG)

And here, you can see that the SignColumn goes away when I delete the marker:
![withoutmarker](https://cloud.githubusercontent.com/assets/1559554/15806395/718557c0-2b10-11e6-8d84-c2b8f9a1c727.PNG)

That is the default behavior

**Comment by krzkrzkrz** [comment]
Yea but isnt there a way to make sure that the SignColumn is always present, regardless if there is a marker present or not?

**Comment by kshenoy** [comment]
Ah, I misunderstood the intent of your question. I thought you were always seeing the SignColumn and wanted to get rid of it.

Well, you can simply place a dummy sign. Vim displays the SignColumn as long as there's 1 sign.

You can add the following to your vimrc:

    sign define Dummy
    autocmd VimEnter  * bufdo execute 'sign place 21358 line=1 name=Dummy buffer=' . bufnr('%')
    autocmd BufNew    * execute 'sign place 21358 line=1 name=Dummy buffer=' . bufnr('%')

**Comment by krzkrzkrz** [comment]
Maybe good to have it as a setting? Maybe call it `SignatureShowAlways`?

**Comment by kshenoy** [comment]
Nope, sorry but that is not a good idea for two reasons:

1. This has got nothing to do with the core functionality of the plugin i.e. showing signs for marks that are placed.
2. This can be easily accomplished by a few lines of vimscript and doesn't require any data from this plugin.

**Comment by Archdsenna** [comment]
> SignColumn

nvim now can do it
set signcolumn=yes:4
