### ISSUE TITLE
Errors when marking extremely large files on 32bit vim

### ISSUE THREAD

**Issue by jkerian** [kshenoy/vim-signature#121]
When I have vim-signature installed (windows, 32bit vim) and try to mark in one of my 3,000,000+ line files, I get an ugly error message from "sign place", with an invalid name.

The cause appears to be this line:   let l:id  = a:lnum * 1000 + bufnr('%')
For a large file on 32bit vim, l:id is wrapping around to a negative number. sign place doesn't appear to accept negative number names.

An easy solution was   let l:id  = abs(a:lnum * 1000 + bufnr('%')), and I've submitted a pull request that does this. (https://github.com/kshenoy/vim-signature/pull/120)

**Comment by kshenoy** [comment]
Nice catch. Thanks for the pull.
