### ISSUE TITLE
conflicts with the Nerdtree  Plugin

### ISSUE THREAD

**Issue by xushaobo** [kshenoy/vim-signature#122]
When I set nerdtree auto-open at startup,
just put the sentence on  .vimrc,
let g:nerdtree_tabs_open_on_console_startup=1   

and then I use mm ,vim-signature can't work well again.

**Comment by kshenoy** [comment]
Hi, sorry for the late response. 

Where do you get the option `g:nerdtree_tabs_open_on_console_startup`? I can't find any option like that in NERDTree's help. Not only that but I can't find any option that uses snake case. All of NERDTree's options only seem to use mixed case.

**Comment by xushaobo** [comment]
Tanks for your replay
So if you add "let g:nerdtree_tabs_open_on_console_startup=1" to ~/.vimrc,and then reboot vim to use the signature plugin ,there's no problem occur?
Fine if so, maybe the error caused by other setting in my vim.

**Comment by xushaobo** [comment]
:help nerdtree

74 ## Configuration
 75
 76 You can switch on/off some features of the plugin by setting global
vars to 1
 77 (for on) or 0 (for off) in your vimrc. Here are the options and their
default
 78 values:
 79
 80 * `let g:nerdtree_tabs_open_on_gui_startup = 1`
 81   Open NERDTree on gvim/macvim startup
 82
 83 * `let g:nerdtree_tabs_open_on_console_startup = 0`
 84   Open NERDTree on console vim startup


2016-07-09 1:40 GMT+08:00 Kartik Shenoy <notifications@github.com>:

**Comment by kshenoy** [comment]
Hi, the `g:nerdtree_tabs_open_on_console_startup` is not an option in [NERDTree](nerdtree_tabs_open_on_console_startup) itself but I found it in [vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs). Is that what you're using?

I installed both NERDTree and vim-nerdtree-tabs and I'm able to see the problem now; Signature doesn't work. Give me some time to figure out what's happening.

**Comment by xushaobo** [comment]
Yes，It's occur to me that  I use the 'Plugin 'jistr/vim-nerdtree-tabs' to auto-open nerdtree for me.
The problem must be caused by it , because  When I only use nerdtree and signture,they work well for me.Thank you for all the trouble you've taken！

**Comment by kshenoy** [comment]
No problem. This is an old bug. The problem is that since NERDTree and Signature have some maps that conflicts, Signature tries to delete its maps when you enter the NERDTree pane and create it again when you leave NERDTree pane.

However, the problem is that entering and leaving NERDTree doesn't trigger the BufLeave and BufEnter autocmd events. See the [discussion](https://github.com/kshenoy/vim-signature/issues/3#issuecomment-222565292) here for more details.

You can try out the fix described in that post in your workarea for the time being.

**Comment by kshenoy** [comment]
Please update and try now.

**Comment by xushaobo** [comment]
Yes now it works fine,
How quick and efficient you are.
and how lucky I'm. haha

2016-07-09 3:34 GMT+08:00 Kartik Shenoy <notifications@github.com>:

**Comment by kshenoy** [comment]
Glad it works. Once again I'm sorry for the late response; I was busy with work.

Since Signature no longer deletes its maps, you might face a small delay when you press `m` in the NERDTree pane. If you want to avoid that, you can change the key used by NERDTree

    let g:NERDTreeMapMenu='M'
