### ISSUE TITLE
E117: Unknown function: strcharpart

### ISSUE THREAD

**Issue by sunaku** [kshenoy/vim-signature#124]
As of commit 485c1f8f5ccaa8a531026641059c940413f1beee:

```
Error detected while processing function signature#sign#Refresh..signature#sign#Place..<SNR>311_RefreshLine:
line   17:
E117: Unknown function: strcharpart
E116: Invalid arguments for function substitute(b:SignatureMarkOrder, "\m", strcharpart(b:sig_marks[a:lnum], 0, 1), '')
E15: Invalid expression: substitute(b:SignatureMarkOrder, "\m", strcharpart(b:sig_marks[a:lnum], 0, 1), '')
line   18:
E117: Unknown function: strcharpart
E116: Invalid arguments for function substitute(l:str,                "\p", strcharpart(b:sig_marks[a:lnum], 1, 1), '')
E15: Invalid expression: substitute(l:str,                "\p", strcharpart(b:sig_marks[a:lnum], 1, 1), '')
line   20:
```

**Comment by kshenoy** [comment]
That's weird. I was able to happily place and remove signs.

Do you get this error as soon as you enter vim? What do I have to do to reproduce this?

**Comment by sunaku** [comment]
It happens when I open a particular file that contains marks (which are remembered in my ~/.viminfo file, I think).  It doesn't occur on normal Vim startup (when just running `vim` or opening a file that has no marks). 

Here is my Vim version:
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 14 2015 15:07:51)
> Included patches: 1-712

And to reproduce the bug:
1. Run `vim /tmp/foo`
2. Insert "hello world"
3. Press `mx` and observe the error
4. Run `:map m` and make sure that it's bound to:
> n  m           * :<C-U>call signature#utils#Input()<CR>

**Comment by sunaku** [comment]
Here's an even simpler diagnostic:

```
:echo exists('*strpart')
1
:echo exists('*strcharpart')
0
```

That new function simply doesn't exist for me.

**Comment by sunaku** [comment]
I also tried this under NeoVim 0.1.4 and found that strcharpart() doesn't exist there either.

**Comment by kshenoy** [comment]
Changed all `strcharpart()` to `strpart()` since I doubt people would specify multibyte characters : /

**Comment by sunaku** [comment]
Works great now, thanks! :+1:
