### ISSUE TITLE
Press ENTER or type command to continue if I open vimrc(all folded)

### ISSUE THREAD

**Issue by vasyapupkin123456** [kshenoy/vim-signature#128]
resolve this problem:
replace in signature.vim
autocmd BufEnter,CmdwinEnter * call signature#sign#Refresh()
to
autocmd BufEnter,CmdwinEnter * silent call signature#sign#Refresh()

**Comment by kshenoy** [comment]
Hi, I don't see this happening. Can you try running this command (assuming you're using Linux) and see if you still get the prompt?

    gvim -N --cmd 'set rtp=$VIM,$VIMRUNTIME,$VIM/after' -U NONE -u <(echo 'set rtp+=~/.vim/bundle/vim-signature')

If not, then it's likely because of some other reason. In that case, check out `:h hit-enter`

**Comment by vasyapupkin123456** [comment]
I set set cmdheight=2 and solve this problem
