### ISSUE TITLE
Conflicts with builtin vim marks for beginning of (and end of) last inserted text

### ISSUE THREAD

**Issue by jaresty** [kshenoy/vim-signature#129]
I would like to use vim-signature but also be able to easily [select the last inserted text in vim ](http://superuser.com/questions/382576/how-to-select-the-last-inserted-text-in-vim).  However, the vim-signature plugin's default keystrokes for GotoNextSpotAlpha (`` `] ``) and GotoPrevSpotAlpha (`` `[ ``) conflict with the builtin marks.  There isn't any way to customize the keystrokes for the plugin or to disable the offending keystrokes, so I am forced to choose between vim's default keystrokes and using the plugin.  I'd be happy if there was a way to simply disable the conflicting keystrokes.

**Comment by kshenoy** [comment]
Take a look at [this](https://github.com/kshenoy/vim-signature/blob/367a28175ac59f1fcbff87fb8f4ee5c66e74b1dc/doc/signature.txt#L91-L121)

Also note that to disable the mapping you have to set it to an empty string.

So, to disable the ones you mentioned you'll have to specify:

      let g:SignatureMap = {
        \ 'GotoNextLineAlpha'  :  "",
        \ 'GotoPrevLineAlpha'  :  "",
        \ }

When I first wrote this, I didn't know about/use the conflicting mappings very often. In hindsight, I agree that it was a bad decision to do that. I guess it's high-time I removed those from the default maps.

**Comment by jaresty** [comment]
That looks great! I like that it will now be possible to override all the
mappings.  Thank you!

Josh

**Comment by jaresty** [comment]
Ah -- it looks like this was already possible.  My bad -- sorry I misread
that documentation.

Josh
