### ISSUE TITLE
Close loclist after selecting mark?

### ISSUE THREAD

**Issue by synic** [kshenoy/vim-signature#134]
Right now the plugin just clears the location list, but leaves it open.

I'd like it to close automatically

**Comment by kshenoy** [comment]
Hi, I'm afraid I won't be able to do this as it fundamentally goes against what the location list is meant for.

However, if you're still interested in doing this, you can add the following map to your vimrc

    :autocmd FileType qf nnoremap <buffer> <CR> <CR>:lclose<CR>

That should do what you want. However, the downside is that it will close the Location List every time you use it outside of this plugin as well.
