### ISSUE TITLE
Conflicts with go to start/end of put.

### ISSUE THREAD

**Issue by trusktr** [kshenoy/vim-signature#135]
Normally you can press ```[`` or ```]`` after pasting with `p` to go to the beginning or end of the pasted content, respectively. However, this overwrites those default mappings. It'd be nice if there was an alternate mapping option?

**Comment by kshenoy** [comment]
Yeah, overwriting vim's default bindings was a bad decision on my part when I first wrote this but I didn't know much about vim then : /

Anyway, add this to your vimrc

      let g:SignatureMap = {
        \ 'GotoNextSpotByPos'  :  "",
        \ 'GotoPrevSpotByPos'  :  "",
        \ }

this will disable the mappings that normally bind ``[` `` and ``]` ``. Relevant section from the [doc](https://github.com/kshenoy/vim-signature/blob/7e13913188809c45e14988270213744d1c3bb485/doc/signature.txt#L133-L134). Hope this helps.

**Comment by trusktr** [comment]
Awesome, thanks!
