### ISSUE TITLE
sync color with gitgutter

### ISSUE THREAD

**Issue by vitaly-zdanevich** [kshenoy/vim-signature#142]
From `README.md`:

_Also supports dynamic highlighting of signs. In the image above the marks are colored according to the state of the line as indicated by gitgutter._

_NOTE: This feature is disabled by default_

So how to enable it?

**Comment by vitaly-zdanevich** [comment]
Sorry I found it in documentation.

**Comment by amarz45** [comment]
Where in the documentation did you find it? I couldn't find it?
