### ISSUE TITLE
vim-signature keeps reporting error on each buffer write

### ISSUE THREAD

**Issue by nthorne** [kshenoy/vim-signature#147]
Hi,

Every now and then, I end up in a state where the error message detailed below appears every time i try to save the buffer. Haven't been able to find a way to reproduce this (or get out of it, other than :q)

Using: neovim v.0.1.7, vim-signature cce7ae4

````
Error detected while processing function signature#sign#Refresh[17]..signature#sign#GetMarkSignLine:
line   10:
Signature: Expected single match, found 2
````

**Comment by nthorne** [comment]
.. by the way; here's the (trimmed) output from ```execute('sign place')```. Is the problem that vim-signature doesn't account for buffer name when checking for matches?

```
Signs for source/test/<foo>.cpp:
...
    line=44  id=44001  name=Signature_w
    line=1  id=666  name=Signature_Dummy
...
Signs for source/<bar>.c:
...
    line=39  id=39004  name=Signature_w
    line=1049  id=1049004  name=Signature_a
    line=1  id=666  name=Signature_Dummy
...
```

**Comment by kshenoy** [comment]
Hi, that piece of code wasn't well thought out and I've commented it out in a later donation. Can you please update and retry?

**Comment by nthorne** [comment]
Hi,

Seems to be working fine now, when that part is commented out. Thanks!
