### ISSUE TITLE
E117: Unknown function: assert_ture.

### ISSUE THREAD

**Issue by Fisher-Chen** [kshenoy/vim-signature#151]
First type ma to add a mark.
When type ma again, it will report this error.
Need to comment out sign.vim line 70 to disable this error message.
`call assert_true(len(l:arr) == 1, "Multiple marks found where one was expected")`

**Comment by kshenoy** [comment]
Is that all that's required to reproduce this error? Type `ma` twice on the same line? It toggles the mark a for me (as it should). Do I need to do anything else to be able to reproduce this?

**Comment by nagakiran** [comment]
I too faced this issue with Vim v7.4.
Noticed that assert_true was added to Vim in v8 and that is the issue
https://github.com/vim/vim/blob/master/runtime/doc/version8.txt#L235

**Comment by kshenoy** [comment]
Sorry for the delay. It should work now. Feel free to reopen in case of any issues.
