### ISSUE TITLE
Settings not respected and m,/m. don't work

### ISSUE THREAD

**Issue by dotfrag** [kshenoy/vim-signature#152]
Hi, I don't know if something is wrong on my side, but I'm having issues with two options (the only I tried so far) and two mappings (m, and m.).

For the command and dot mappings I get the following error:

> Error detected while processing function signature#mark#Toggle[10]..<SNP>76_ReportNoAvailableMarks
> Signature: No free marks left.

Maybe I didn't understand how they work but they should add the next available marker yes?

And the settings I have are:
```
let g:SignatureDeleteConfirmation = 1
let g:SignaturePurgeConfirmation = 1
```

But none of these are respected, m space deletes all markers without confirmation. I have Space set as my leader key, could that be a conflict?

EDIT: Forgot to mention, m- doesn't work either.

**Comment by shaggyrogers** [comment]
This should be fixed now.

**Comment by dotfrag** [comment]
Thank you, it's much more usable now! I've noticed another bug, if you press m- or m<space> you get a Y/N prompt to confirm deletion. If you press Esc, it counts as Yes. It's a minor thing but in Vim we are used to spam the Esc key and I keep doing it by habit. If you could fix that it'd be perfect. Thanks again for the quick response.

**Comment by kshenoy** [comment]
@shaggyrogers Thanks for the fix. 
@dotfrag Sorry, I've been busy at work; I'll take a look at that this weekend.

**Comment by kshenoy** [comment]
Hi @dotfrag, sorry for the delay. Give this a try now.

**Comment by dotfrag** [comment]
No problem at all. Works perfectly, thank you @kshenoy !
