### ISSUE TITLE
Marks are shown very bright

### ISSUE THREAD

**Issue by sdicke** [kshenoy/vim-signature#155]
I tested the plugin with much different colorschemes and with every colorscheme the marks are displayed in a bright pink color which are not good visible. 

Vim version: 8.0.1531-1

**Comment by kshenoy** [comment]
@sdicke The default color for marks is red. You can redefine it if you want like so:

    :highlight SignatureMarkText guifg <color>

Look up `:h :highlight` for more information.

You can also set `g:SignatureMarkTextHL` to an existing highlight group using `let g:SignatureMarkTextHL = Error`
