### ISSUE TITLE
Invalid character in group name error on startup

### ISSUE THREAD

**Issue by mMontu** [kshenoy/vim-signature#163]
I'm experiencing a issue similar to #109 -- on startup I receive the following message:

    Error detected while processing function signature#sign#Refresh[22]..signature#sign#Place[30]..<SNR>146_RefreshLine:
    line   20:
    W18: Invalid character in group name
    W18: Invalid character in group name

It started happening after I updated the vim-signature plugin.

Following the suggestion on the similar issue, I tested starting vim without any custom setting or any other plugin, and the error doesn't happen. In fact, the error only happens in the vim session I use most frequently -- I couldn't reproduce it using a smaller setup.

Adding an echo before [the line causing the error](https://github.com/kshenoy/vim-signature/blob/master/autoload/signature/sign.vim#L129):

    echom 'sign define Signature_' . l:str . ' text=' . l:str . ' texthl=' . l:SignatureMarkTextHL . ' linehl=' . l:SignatureMarkLineHL

, I got the following:

    sign define Signature_z text=z texthl="Exception" linehl=""

I didn't dig much in the logic, but forcing the default values listed in the documentation for variables `g:SignatureMarkLineHL` and `g:SignatureMarkTextHL` fixed the issue:

    function! s:RefreshLine(lnum)                                                                                      "{{{1
        " ...
        let l:SignatureMarkTextHL = s:EvaluateHL(g:SignatureMarkTextHL, a:lnum, "SignatureMarkText")
        let l:SignatureMarkLineHL = s:EvaluateHL(g:SignatureMarkLineHL, a:lnum, "SignatureMarkLine")
        let l:str = substitute(b:SignatureMarkOrder, "\m", strpart(b:sig_marks[a:lnum], 0, 1), '')
        let l:str = substitute(l:str,                "\p", strpart(b:sig_marks[a:lnum], 1, 1), '')
    
        let l:SignatureMarkLineHL = 'SignatureMarkLine'
        let l:SignatureMarkTextHL = 'Exception'
        " echom 'sign define Signature_' . l:str . ' text=' . l:str . ' texthl=' . l:SignatureMarkTextHL . ' linehl=' . l:SignatureMarkLineHL
        execute 'sign define Signature_' . l:str . ' text=' . l:str . ' texthl=' . l:SignatureMarkTextHL . ' linehl=' . l:SignatureMarkLineHL

Clearly this isn't a proper solution. Can you please give some pointers about how to further debug this?

**Comment by kshenoy** [comment]
Hello, sorry for not responding any sooner; there were a lot of other things vying for my time. Please let me know if this is still an issue

**Comment by mMontu** [comment]
Hi @kshenoy, no worries.

This issue doesn't occur anymore. To be honest I don't recall when or why the workaround I mentioned above is not necessary anymore (for the record, I'm using hash 968622e9).

Thanks!
