### ISSUE TITLE
Delete mark via location list

### ISSUE THREAD

**Issue by YodaEmbedding** [kshenoy/vim-signature#169]
When the location list is opened via `m/`, it would be nice to be able to `dd` away any undesired marks.

**Comment by kshenoy** [comment]
Hello @YodaEmbedding. I'm sorry but I don't think I'd be supporting this request. 

LocationList is meant to obtain a filtered view into the buffer and any operations performed there are not meant to propagate to the buffer itself. Your feature request would violate this general principle.

Furthermore, one can argue that by pressing `dd` in any buffer, one intuitively expects the buffer itself to get modified. And while the LocationList isn't a regular buffer, it is not too far-fetched to assume that one would expect it to behave similarly. Thus, by implementing this we'd also be subverting that expectation.
