### ISSUE TITLE
can signature#mark#list show the postion of ".", "'",  "`", etc? 

### ISSUE THREAD

**Issue by Freed-Wu** [kshenoy/vim-signature#173]
i have noticed this plugin is better than many other plugins. but it looks like signature#mark#list cannot show  the postion of ".", "'",  "`", etc, like MarksBrowser
![2020-03-17 15-03-10 的屏幕截图](https://user-images.githubusercontent.com/32936898/76830568-75292000-6860-11ea-90fc-9e286445aa2f.png)

it is an enhancement. Thanks!

**Comment by kshenoy** [comment]
Hello, I've thought about adding that but then I couldn't find a compelling reason to do because I'd just be duplicating the built-in functionality of `:marks` without adding anything new. So I'm still on the fence on this.

**Comment by kshenoy** [comment]
Duplicates #36
