### ISSUE TITLE
How to turn off this plugin by default ?

### ISSUE THREAD

**Issue by cs-pchsu** [kshenoy/vim-signature#174]
Hi,

I have a question "How to turn off this plugin by default".
When I need it, I will use the :SignatureToggle to enable it.

I tried to achieve this using the following method in my .vimrc, but an error occurred.
.vimrc:
au BufEnter * :SignatureToggle <CR>
error:
Error detected while processing BufEnter Auto commands for "*":
E488: Trailing characters: :SignatureToggle <CR>

Thanks for your reply

**Comment by kshenoy** [comment]
Use `let g:SignatureEnabledAtStartup=0`. You can explicitly enable it using `:SignatureToggleSigns`

**Comment by cs-pchsu** [comment]
Hi @kshenoy 

Thanks for your reply.
The method you provide solve my problem.
