### ISSUE TITLE
[bug] mark cannot be deleted

### ISSUE THREAD

**Issue by Freed-Wu** [kshenoy/vim-signature#185]
```vim
" $ uname -r
" 5.13.8-arch1-1
" $ has nvim
" ✓ nvim 0.5.0
" $ has python
" ✓ python 3.9.6
" $ vi test.vim
set runtimepath=$VIMRUNTIME,~/.local/share/nvim/repos/github.com/kshenoy/vim-signature
" $ vi -u test.vim test.vim
```

press `ma`
![Screenshot from 2021-08-15 13-28-35](https://user-images.githubusercontent.com/32936898/129468246-c5d68f35-12af-4774-bc49-e124229b2fbb.png)

press `ZZ`, then
```shell
$ vi -u test.vim test.vim
```

press `m-`
![Screenshot from 2021-08-15 13-28-40](https://user-images.githubusercontent.com/32936898/129468252-a2f1727a-de06-465a-b9ba-0b91cd40e18b.png)

press `ZZ`, then
```shell
$ vi -u test.vim test.vim
```
![Screenshot from 2021-08-15 13-28-35](https://user-images.githubusercontent.com/32936898/129468259-b77c347c-5d09-41e2-be59-f455cb8aad30.png)

the deleted mark `a` occurred again.

NOTE: must press `ZZ` to quit once, if `mam-ZZ` then `vi -u test.vim test.vim`, the mark will not occur.

**Comment by cpkio** [comment]
This is Neovim _feature_ not to save removal of marks in shada file. Fix with force writing shada file on exit: `autocmd VimLeave * wshada!`

**Comment by Freed-Wu** [comment]
You are great!

Perhaps this tip can help more people.

Thanks!
