### ISSUE TITLE
what's differences mark from marker

### ISSUE THREAD

**Issue by pycj** [kshenoy/vim-signature#187]
Thanks your plugin first!
so, "m?" is means that LocalListMarkers , so what's differences from "m\\"
and i dont't know why my "m<space>" dont't work.
thank you.

**Comment by pycj** [comment]
solved。sorry

**Comment by kshenoy** [comment]
Hello, sorry about the late response. Between work and me migrating away from vim, I haven't been able to pay much attention to this plugin. 

Marks are built into vim and you can use all the lowercase characters as marks but each of them can only be placed once per buffer. There's also the uppercase characters but those are global in scope and can only be used 1 per uppercase character across all the files.

I felt this was limiting while browsing code and I wanted to use the same sign multiple times which wasn't supported by marks. So this plugin adds what I'm calling marker support. To be visually distinct, it uses the symbols above the number row (on the standard qwerty keyboard layout). Each of these symbols can be placed multiple times
