### ISSUE TITLE
Marks don't always show immediately

### ISSUE THREAD

**Issue by gpakosz** [kshenoy/vim-signature#27]
Steps to reproduce:
1. open vim
2. write some text
3. set a mark, e.g. `ma`

The mark doesn't immediately show up on the screen. After some timeout, then it finally appears

**Comment by haitongz** [comment]
this problem occur again on my MacVim

**Comment by kshenoy** [comment]
@haitongz can you try starting vim with the following command (change the path to wherever you have installed vim-signature):

    vim -Nu <(echo 'set rtp+=~/.vim/bundle/vim-signature/')

This will open vim with just vim-signature installed. Check if you're still facing the problem.
If not, then it means some other plugin is interfering with the maps. In either case, what's the output of `:verb map m`?

**Comment by haitongz** [comment]
@kshenoy I restart my MacVim, it works. thx
