### ISSUE TITLE
Error detected while processing function ToggleSign

### ISSUE THREAD

**Issue by Jobeo** [kshenoy/vim-signature#53]
This error has been coming up for me sporadically.  It happens when I try to set a mark which is already set in some other place.

I don't know how to capture the error messages as it closes the window whenever I click on it.  I captured them as an image:

![vim-signature](https://cloud.githubusercontent.com/assets/3967525/3510500/4239f65e-06a7-11e4-93b7-862604844549.png)

**Comment by kshenoy** [comment]
I hope the issue is resolved. If not, please feel free to reopen it.
