### ISSUE TITLE
Support Signify (like gitgutter)

### ISSUE THREAD

**Issue by unphased** [kshenoy/vim-signature#77]
Signify is like gitgutter, except it works better, and superior in many ways. 

See #42.

**Comment by michaelmior** [comment]
I didn't notice this issue until after, but managed to get something basic working for myself

```vim
" Add vim-signify highlighting to vim-signature
function! SignatureVimSignify(lnum)
  call sy#sign#get_current_signs()

  if has_key(b:sy.internal, a:lnum)
    let type = b:sy.internal[a:lnum]['type']
    if type =~ 'SignifyAdd'
      return 'DiffAdd'
    elseif type =~ 'SignifyChange'
      return 'DiffChange'
    elseif type =~ 'SignifyDelete'
      return 'DiffDelete'
    end
  else
    return 'Exception'
  endif
endfunction

let g:SignatureMarkTextHL = 'SignatureVimSignify(a:lnum)'
```

**Comment by michaelmior** [comment]
To me, it seems like it would make sense to detect if plugins like these exist and assign `SignatureMarkTextHL` accordingly. Of course this does mean that they will require some maintenance when the plugins change, but it seems better than posting snippets of code like the above in other locations and leaving others to figure it out when it breaks.

**Comment by kshenoy** [comment]
I prefer to keep code contained and have as few dependencies as possible. In this case, if I include all these in the code, then function for GitGutter would be if someone uses Signify and vice-versa. That is why I didn't want to include it in this repo.

However, you raise a very valid point. I think I'll probably create separate plugins of these so that anyone who is interested can install whichever they want.

Also, thanks a lot for coding this up. I had completely forgotten about this.

**Comment by michaelmior** [comment]
There are no dependencies necessary. You can simply check and see if either of the plugins is installed and conditionally enable support.

**Comment by michaelmior** [comment]
For example, vim-airline does this for all of it's various extensions. If you check the top few lines of each of the files in the extensions folder, there's a small check to see if the extension is installed.

https://github.com/bling/vim-airline/tree/master/autoload/airline/extensions

**Comment by kshenoy** [comment]
Fair enough. Just had a discussion today at work about convenience for the designer vs convenience for the end-user and to cut a long story short, I've added support for these :)

**Comment by michaelmior** [comment]
Thanks! Just tested this out and it works great :)

**Comment by kshenoy** [comment]
Np. And thanks once again for implementing this for Signify :)
