### ISSUE TITLE
Moving Last Mark

### ISSUE THREAD

**Issue by orbisvicis** [kshenoy/vim-signature#81]
This action - moving the last mark - quickly toggles the display of the SignColoumn, which is visually disturbing. Is there anything that can be done, perhaps:

* add the new mark before deleting the old mark (even possible?)
* hide+change the old mark before adding the new mark
* force the sign column display, temporarily

**Comment by kshenoy** [comment]
Wow, that's badly broken. I'm not able to move any mark :(
Give me some time to figure out what's wrong.

**Comment by kshenoy** [comment]
Can you give it a try now?

**Comment by orbisvicis** [comment]
Thanks; it's fixed.
