### ISSUE TITLE
Jump to next mark across buffers

### ISSUE THREAD

**Issue by andreasthoelke** [kshenoy/vim-signature#84]
Signature works very well for me, thank you! There is one feature I'm missing however: 

I would like to rotate through all marks across buffers using the next/prev mark commands. I think this would facilitate buffer navigation greatly, also I would not have to memorize the mark IDs, but could just maintain a short list of places that I can rotate through.

I think it would be great if we had a "Jump to next/prev mark across buffers" command. These jumps should then probably only consider capital letter IDs.

Alternatively a `g:SignatureJumpsAcrossBuffers` option could allow to make all "Jump to/by" commands "Across buffers".

I looked into `s:GotoByAlpha(dir)` - and passing `'buf_all'` to `signature#mark#GetList`, but of cause it's not that easy.

**Comment by kshenoy** [comment]
Interesting! Give me some time to think about this.

**Comment by kshenoy** [comment]
Can you give it a try now? I didn't create default maps for it (since I can't think of any good ones). You'll have to do it yourself. Something like

    nnoremap ]" :<C-U>call signature#mark#Goto("next", "spot", "global")
    nnoremap [" :<C-U>call signature#mark#Goto("prev", "spot", "global")

**Comment by kshenoy** [comment]
I'm assuming this works and closing this request. If not, please reopen it.

**Comment by andreasthoelke** [comment]
Awesome, this works exactly as expected! I think it makes working across several files a lot faster/more convenient. I mapped it to the home raw:

```
nnoremap <c-space><c-j> :<C-U>call signature#mark#Goto("next", "spot", "global")<CR>
nnoremap <c-space><c-h> :<C-U>call signature#mark#Goto("prev", "spot", "global")<CR>`
```

Thanks for turning this around so quickly!!

**Comment by kshenoy** [comment]
Np, the Goto() function can also take the _line_ argument

    call signature#mark#Goto("next", "line", "global")<CR>

like so if you want to jump only to the line and not necessarily the spot (dunno why you'd wanna do that or why I even added it but it exists... : / )
