### ISSUE TITLE
Vundle installation: error detected while processing signature.vim: Unknown function: signature#util#Set

### ISSUE THREAD

**Issue by kflu** [kshenoy/vim-signature#97]
I got this error when installing it via Vundle. And after the installation, subsequent vim launches will not have this issue. However, helptags are not generated. I'm using Windows and Vundle it that matters.

    error detected while processing signature.vim: Unknown function: signature#util#Set

![untitled](https://cloud.githubusercontent.com/assets/1031978/10903944/081f6622-81c4-11e5-9dca-68ef7e6c08fb.png)

**Comment by kshenoy** [comment]
This most probably is a bug with Vundle itself. It doesn't seem to be sourcing any other file from the plugin folder upon installation. 

I filed an [issue](https://github.com/VundleVim/Vundle.vim/issues/666) against them.

**Comment by AguirreIF** [comment]
Hi, I was having exactly the same issue with [pathogen](https://github.com/tpope/vim-pathogen). I moved the file `plugin/signature/utils.vim` to `autoload/signature/utils.vim` and now its working great.

**Comment by kshenoy** [comment]
@AguirreIF The file `plugin/signature/utils.vim` is not intended to be moved to the autoload directory. If doing so helps then pathogen might have the same bug as Vundle

**Comment by lcd047** [comment]
I have the exact same problem testing the new package system in recent Vim versions (see `:h packages` in Vim 7.4.1553 or later).  A function named `signature#util#Set()` is an autoload function, and it's supposeed to live in a file `autoload/signature/utils.vim`, with the `autoload` directory in `runtimepath` (see `:h autoload` for more information).  If it works at all in a different file, that's a misfeature of the plugin manager you're using, and it's going to break in recent versions of Vim.  So, intended or not, moving `plugin/signature/utils.vim`  to  `autoload/signature/utils.vim` is the proper solution. _shrug_

**Comment by kshenoy** [comment]
@lcd047 Thanks for pointing me to `:h autoload-functions`

Moved utils.vim to autoload directory since the documentation clearly states that vim will search for a function `filename#funcname()` in autoload directories in runtimepath.

Closed bug against Vundle too.
