### ISSUE TITLE
vim-signature produces several errors after latest commit

### ISSUE THREAD

**Issue by hallzy** [kshenoy/vim-signature#98]
upon opening any file with vim after the last commit I get these errors before the document loads:

![screenshot from 2015-11-07 11 53 26](https://cloud.githubusercontent.com/assets/5404143/11017003/9ce85702-8546-11e5-8b93-9d45fff58e06.png)

And about ever 10 or so seconds the same errors pop up, probably while signature tries to update.

```bash
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
Included patches: 1-52
```

**Comment by kshenoy** [comment]
That doesn't make sense. It doesn't give those errors for me. Can you remove it and then reinstall it and see if it helps.

**Comment by hallzy** [comment]
Ya that did it. Thanks.

The problem was that I just copy the files over to my ~/.vim folder, but did not realize that some of the files had changed locations, so I never removed the old files and I guess that got something confused.
