### ISSUE TITLE
Bug when displaying uppercase marks?

### ISSUE THREAD

**Issue by gpakosz** [kshenoy/vim-signature#99]
Here are the steps:

- open `foo.txt`, set mark `A`
- open `bar.txt`, set mark `B`, and also set mark `A`
- `:bn` to get back to `foo.txt`

By now, when issuing `:call signature#mark#List('buf_curr')` for `foo.txt`, the list of current mark is empty. Yet, mark `A` is still being displayed.

**Comment by kshenoy** [comment]
Interesting. Thanks for letting me know. 

It seems it doesn't refresh the global marks at all. The same incorrect persistence is seen even if you just place `A` in bar.txt without placing `B`

I'll get back to you when I learn more.

**Comment by kshenoy** [comment]
Hmm, looks like it was incorrectly identifying "free marks" when it came to globals. Give it a whirl now.

**Comment by gpakosz** [comment]
Seems to work now. Thanks!
